[functions.kajabi-webhook]
verify_jwt = false

[functions.paypal-webhook]
verify_jwt = false

[functions.invite-staff-member]
verify_jwt = true

[functions.reset-staff-password]
verify_jwt = true
